name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Compile
      run: yarn run vscode:prepublish

    - name: Run tests
      run: xvfb-run -a yarn test
      if: runner.os == 'Linux'

    - name: Run tests
      run: yarn test
      if: runner.os != 'Linux'
